### PR TITLE
Reorder fields to create fewer merge conflicts

### PR DESCRIPTION
**Pull request by cgrail**

### CODE REVIEW

**Comment by cgrail** [comment]
Hi @nimzco

I accidently commited a PR to the main branch. I wanted to create a PR.
I was thinking whether we could reorder the fields, so that we get fewer merge conflicts. Currently the online flag is most of the time the last property and git doesn't treat it as it belongs to one conference. If we could move the url as last field, I hope we'll get fewer merge conflicts.

**Comment by cgrail** [comment]
The main change was done here: https://github.com/tech-conferences/api.confs.tech/commit/e2b81908214b6e5a7229298d6679676b510838a3#diff-1477c338c3187fa7d0a350d3d9f3421d81f2cdf22dae0dca1593f7373e72a487

**Comment by cgrail** [comment]
@nimzco - ok you already fixed it

**Comment by nimzco** [comment]
Ah shoe I hadn’t seen your ping!
Can you link me to a mn example of a conflict? I’ll have a look next week!

**Pull request closed without merging**
